name: gobooks
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_messaging: ^11.4.2
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  lottie: ^1.3.0
  flutter_svg: ^1.0.3
  carousel_slider: ^4.1.1
  cloud_firestore: ^3.1.17
  firebase_auth: ^3.3.19
  firebase_core: ^1.17.1
  firebase_database: ^9.0.15
  provider: ^6.0.3
  google_sign_in: ^5.3.3
  firebase_storage: ^10.2.17
  file_picker: ^4.6.1
  date_field: ^3.0.1
#<<<<<<< Updated upstream
  flutter_local_notifications: ^9.4.0
#  flutter_local_notifications: ^9.6.1
#=======
#  flutter_local_notifications: ^9.6.1
  android_alarm_manager_plus: ^2.0.6
  shared_preferences: ^2.0.15
  rxdart: ^0.27.4
  timezone: ^0.8.0
  
#>>>>>>> Stashed changes
#  android_alarm_manager_plus: ^2.0.5
#  rxdart: ^0.27.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/lottie/